[book]
authors = ["Luos"]
language = "en"
multilingual = false
src = "src"
title = "Luos.io - Documentation"
description = "Luos official documentation pages"

[output.html]
theme = "src/theme"
additional-css = ["src/_assets/css/custom.css"]
google-analytics = "UA-153509818-3"
